### ISSUE TITLE
Jumpssh Issue while establishing SSH with remote Alcatel Router

### ISSUE THREAD

**Issue by mohammedtalo** [AmadeusITGroup/JumpSSH#110]
Hi,

Hope this discussion finds everyone well during this crisis.

I am using Jumpssh from RedHat server to Alcatel Router ( in the middle is Another RedHat server)

I have read all documents and i am following all the steps correctly but i am getting Error.

Here is the code!

from jumpssh import SSHSession

server_session = SSHSession('10.10.10.100', 'mohammed', password = 'python').open() 
### i am getting output

switch_session = server_session.get_remote_session('10.10.10.2', 'admin', password = 'python')
## when i do print(switch_session.is_active()) i am getting True

print(switch_session.get_cmd_output('show port'))

# i am getting Error when i use show port or any command

server_session.close()

and I am getting this Error 

Traceback (most recent call last):

  File "new.py", line 9, in <module>

    print(switch_session.get_cmd_output("show port"))

  File "/usr/local/lib/python3.6/site-packages/jumpssh/session.py", line 419, in get_cmd_output

    return self.run_cmd(cmd=cmd, **kwargs).output

  File "/usr/local/lib/python3.6/site-packages/jumpssh/session.py", line 307, in run_cmd

    channel.exec_command(my_cmd)

  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 72, in _check

    return func(self, *args, **kwds)

  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 257, in exec_command

    self._wait_for_event()

  File "/usr/local/lib/python3.6/site-packages/paramiko/channel.py", line 1226, in _wait_for_event

    raise e

  File "/usr/local/lib/python3.6/site-packages/paramiko/transport.py", line 2055, in run

    ptype, m = self.packetizer.read_message()

  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 459, in read_message

    header = self.read_all(self.__block_size_in, check_rekey=True)

  File "/usr/local/lib/python3.6/site-packages/paramiko/packet.py", line 303, in read_all

    raise EOFError()

EOFError

I am looking for your help ! 

Thanks

**Comment by t-cas** [comment]
Hi @mohammedtalo,

it is possible that your Alcatel router does not support or allow `exec_command()` used by jumpssh from underlined paramiko library (similar issue mentioned [here](https://stackoverflow.com/questions/48789499/what-is-the-meaning-of-the-eoferror-after-i-execute-a-command-with-paramiko))
You can verify this by manually running following SSH command (from a shell):
`ssh admin@10.10.10.2 show port`
If this command is failing, you will have to use the `invoke_shell` from paramiko interface.
From your switch SSHSession, you can use it with something like:
```
channel = switch_session.ssh_transport.open_session()
channel.get_pty()
channel.invoke_shell()
channel.send('show port\n')
output = channel.recv(1024)
print(output)
```
You can check [Paramiko channel documentation](http://docs.paramiko.org/en/stable/api/channel.html) for more details on this interface.

**Comment by mohammedtalo** [comment]
Thanks Man i manage to do exactly what you have told me and it is working.

Really Appreciate your support and help.
